// AUTO-GENERATED by _asset-tools/export_archive.mjs — do not edit by hand.
// The real portfolio (2019–23), exported page-for-page from the source PDF.
export type ArchiveSlide = {
  n: number;
  page: number;
  src: string;
  zoom: string;
  w: number;
  h: number;
  label: string;
  role: string;
};

export type ArchiveProject = {
  slug: string;
  name: string;
  year: string;
  discipline: string;
  accent: string;
  oneLine: string;
  thumb: string;
  slideCount: number;
  slides: ArchiveSlide[];
};

export const ARCHIVE_COVER = {
  "src": "/images/archive/cover/cover.jpg",
  "zoom": "/images/archive/cover/cover@2x.jpg",
  "w": 1600,
  "h": 900
} as const;

export const ARCHIVE_PROJECTS: ArchiveProject[] = [
  {
    "slug": "stun-gun",
    "name": "Stun Gun for Women",
    "year": "2019–23",
    "discipline": "Industrial design",
    "accent": "#A85F45",
    "oneLine": "Industrial/product design of a sleek rose-gold self-defense stun gun for women — a student concept styled after Lockheed Martin's aircraft aesthetics (speculative brand treatment).",
    "thumb": "/images/archive/stun-gun/thumb.jpg",
    "slideCount": 5,
    "slides": [
      {
        "n": 1,
        "page": 2,
        "src": "/images/archive/stun-gun/s1.jpg",
        "zoom": "/images/archive/stun-gun/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Stun Gun For Women",
        "role": "cover"
      },
      {
        "n": 2,
        "page": 3,
        "src": "/images/archive/stun-gun/s2.jpg",
        "zoom": "/images/archive/stun-gun/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Context Analysis",
        "role": "context"
      },
      {
        "n": 3,
        "page": 4,
        "src": "/images/archive/stun-gun/s3.jpg",
        "zoom": "/images/archive/stun-gun/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Stun Gun Concept",
        "role": "concept"
      },
      {
        "n": 4,
        "page": 5,
        "src": "/images/archive/stun-gun/s4.jpg",
        "zoom": "/images/archive/stun-gun/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Features",
        "role": "features"
      },
      {
        "n": 5,
        "page": 6,
        "src": "/images/archive/stun-gun/s5.jpg",
        "zoom": "/images/archive/stun-gun/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Conclusion",
        "role": "conclusion"
      }
    ]
  },
  {
    "slug": "lotus-heater",
    "name": "Lotus Room Heater",
    "year": "2019–23",
    "discipline": "Industrial design",
    "accent": "#9A7B4F",
    "oneLine": "Industrial design of a circular, lotus-petal-embossed convection room heater for Indian households, with a companion thermostat app.",
    "thumb": "/images/archive/lotus-heater/thumb.jpg",
    "slideCount": 7,
    "slides": [
      {
        "n": 1,
        "page": 7,
        "src": "/images/archive/lotus-heater/s1.jpg",
        "zoom": "/images/archive/lotus-heater/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Room Heater",
        "role": "concept"
      },
      {
        "n": 2,
        "page": 8,
        "src": "/images/archive/lotus-heater/s2.jpg",
        "zoom": "/images/archive/lotus-heater/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Problems with existing room heaters / My concept",
        "role": "problem"
      },
      {
        "n": 3,
        "page": 9,
        "src": "/images/archive/lotus-heater/s3.jpg",
        "zoom": "/images/archive/lotus-heater/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Inspired by the lotus",
        "role": "process"
      },
      {
        "n": 4,
        "page": 10,
        "src": "/images/archive/lotus-heater/s4.jpg",
        "zoom": "/images/archive/lotus-heater/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Final Product",
        "role": "results"
      },
      {
        "n": 5,
        "page": 11,
        "src": "/images/archive/lotus-heater/s5.jpg",
        "zoom": "/images/archive/lotus-heater/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Features",
        "role": "features"
      },
      {
        "n": 6,
        "page": 12,
        "src": "/images/archive/lotus-heater/s6.jpg",
        "zoom": "/images/archive/lotus-heater/s6@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "The Heater App",
        "role": "features"
      },
      {
        "n": 7,
        "page": 13,
        "src": "/images/archive/lotus-heater/s7.jpg",
        "zoom": "/images/archive/lotus-heater/s7@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Conclusion",
        "role": "conclusion"
      }
    ]
  },
  {
    "slug": "yaap",
    "name": "YAAP IG Creatives",
    "year": "2019–23",
    "discipline": "Graphic design · Social",
    "accent": "#5B5AA8",
    "oneLine": "Social-media graphic-design campaign: a series of minimalist, concept-driven Instagram post creatives for the yaap.official handle.",
    "thumb": "/images/archive/yaap/thumb.jpg",
    "slideCount": 5,
    "slides": [
      {
        "n": 1,
        "page": 14,
        "src": "/images/archive/yaap/s1.jpg",
        "zoom": "/images/archive/yaap/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "YAAP digital’s Instagram Creatives.",
        "role": "concept"
      },
      {
        "n": 2,
        "page": 15,
        "src": "/images/archive/yaap/s2.jpg",
        "zoom": "/images/archive/yaap/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Minimalism in Design",
        "role": "features"
      },
      {
        "n": 3,
        "page": 16,
        "src": "/images/archive/yaap/s3.jpg",
        "zoom": "/images/archive/yaap/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Gestalt Principles",
        "role": "process"
      },
      {
        "n": 4,
        "page": 17,
        "src": "/images/archive/yaap/s4.jpg",
        "zoom": "/images/archive/yaap/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Impact and Results",
        "role": "results"
      },
      {
        "n": 5,
        "page": 18,
        "src": "/images/archive/yaap/s5.jpg",
        "zoom": "/images/archive/yaap/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Conclusion",
        "role": "conclusion"
      }
    ]
  },
  {
    "slug": "obc",
    "name": "OBC Bank Redesign",
    "year": "2019–23",
    "discipline": "UX/UI · Banking",
    "accent": "#1F7A3D",
    "oneLine": "UI/UX redesign of the Oriental Bank of Commerce website and mobile banking app, covering personas, wireframes and key flows.",
    "thumb": "/images/archive/obc/thumb.jpg",
    "slideCount": 6,
    "slides": [
      {
        "n": 1,
        "page": 19,
        "src": "/images/archive/obc/s1.jpg",
        "zoom": "/images/archive/obc/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "OBC Bank Website & App Redesign",
        "role": "title"
      },
      {
        "n": 2,
        "page": 20,
        "src": "/images/archive/obc/s2.jpg",
        "zoom": "/images/archive/obc/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "OBC Bank Website & App",
        "role": "process"
      },
      {
        "n": 3,
        "page": 21,
        "src": "/images/archive/obc/s3.jpg",
        "zoom": "/images/archive/obc/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Website wire frames",
        "role": "process / features"
      },
      {
        "n": 4,
        "page": 22,
        "src": "/images/archive/obc/s4.jpg",
        "zoom": "/images/archive/obc/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Bill Payments Page",
        "role": "features"
      },
      {
        "n": 5,
        "page": 23,
        "src": "/images/archive/obc/s5.jpg",
        "zoom": "/images/archive/obc/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "App Wireframes",
        "role": "features"
      },
      {
        "n": 6,
        "page": 24,
        "src": "/images/archive/obc/s6.jpg",
        "zoom": "/images/archive/obc/s6@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Apply For Credit Card",
        "role": "features"
      }
    ]
  },
  {
    "slug": "vsg",
    "name": "VSG Website Redesign",
    "year": "2019–23",
    "discipline": "UX/UI · Client work",
    "accent": "#C0263B",
    "oneLine": "End-to-end UX/UI website redesign case study for VSG, a Dover company, spanning brief, research, IA, wireframes, prototypes and development.",
    "thumb": "/images/archive/vsg/thumb.jpg",
    "slideCount": 10,
    "slides": [
      {
        "n": 1,
        "page": 25,
        "src": "/images/archive/vsg/s1.jpg",
        "zoom": "/images/archive/vsg/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "VSG",
        "role": "cover / title"
      },
      {
        "n": 2,
        "page": 26,
        "src": "/images/archive/vsg/s2.jpg",
        "zoom": "/images/archive/vsg/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Project Brief",
        "role": "context"
      },
      {
        "n": 3,
        "page": 27,
        "src": "/images/archive/vsg/s3.jpg",
        "zoom": "/images/archive/vsg/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Competitor Analysis & Insights",
        "role": "process"
      },
      {
        "n": 4,
        "page": 28,
        "src": "/images/archive/vsg/s4.jpg",
        "zoom": "/images/archive/vsg/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Personas & Journey Maps",
        "role": "process"
      },
      {
        "n": 5,
        "page": 29,
        "src": "/images/archive/vsg/s5.jpg",
        "zoom": "/images/archive/vsg/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Solutions",
        "role": "process"
      },
      {
        "n": 6,
        "page": 30,
        "src": "/images/archive/vsg/s6.jpg",
        "zoom": "/images/archive/vsg/s6@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Information Architecture",
        "role": "process"
      },
      {
        "n": 7,
        "page": 31,
        "src": "/images/archive/vsg/s7.jpg",
        "zoom": "/images/archive/vsg/s7@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Wire-framing",
        "role": "process"
      },
      {
        "n": 8,
        "page": 32,
        "src": "/images/archive/vsg/s8.jpg",
        "zoom": "/images/archive/vsg/s8@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Prototyping",
        "role": "process"
      },
      {
        "n": 9,
        "page": 33,
        "src": "/images/archive/vsg/s9.jpg",
        "zoom": "/images/archive/vsg/s9@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Development",
        "role": "process"
      },
      {
        "n": 10,
        "page": 34,
        "src": "/images/archive/vsg/s10.jpg",
        "zoom": "/images/archive/vsg/s10@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Conclusion",
        "role": "conclusion"
      }
    ]
  },
  {
    "slug": "music-rooms",
    "name": "Music Rooms",
    "year": "2019–23",
    "discipline": "UX · Concept",
    "accent": "#5B5A8A",
    "oneLine": "Concept/UX design for a social music app with collaborative 'rooms', shared queues, sound deck and live listening features.",
    "thumb": "/images/archive/music-rooms/thumb.jpg",
    "slideCount": 4,
    "slides": [
      {
        "n": 1,
        "page": 35,
        "src": "/images/archive/music-rooms/s1.jpg",
        "zoom": "/images/archive/music-rooms/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Music Rooms",
        "role": "title"
      },
      {
        "n": 2,
        "page": 36,
        "src": "/images/archive/music-rooms/s2.jpg",
        "zoom": "/images/archive/music-rooms/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Collaborative playlist",
        "role": "features"
      },
      {
        "n": 3,
        "page": 37,
        "src": "/images/archive/music-rooms/s3.jpg",
        "zoom": "/images/archive/music-rooms/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Features",
        "role": "features"
      },
      {
        "n": 4,
        "page": 38,
        "src": "/images/archive/music-rooms/s4.jpg",
        "zoom": "/images/archive/music-rooms/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Sound Deck",
        "role": "features"
      }
    ]
  },
  {
    "slug": "best",
    "name": "BEST Bus Service",
    "year": "2019–23",
    "discipline": "UX research · Transit",
    "accent": "#E0303A",
    "oneLine": "UX research and app design for Mumbai's BEST public buses — a transit app for tracking, boarding, exploring routes and booking fares.",
    "thumb": "/images/archive/best/thumb.jpg",
    "slideCount": 12,
    "slides": [
      {
        "n": 1,
        "page": 39,
        "src": "/images/archive/best/s1.jpg",
        "zoom": "/images/archive/best/s1@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "B.E.S.T Service",
        "role": "cover"
      },
      {
        "n": 2,
        "page": 40,
        "src": "/images/archive/best/s2.jpg",
        "zoom": "/images/archive/best/s2@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "The Question which gave birth to the project.",
        "role": "problem"
      },
      {
        "n": 3,
        "page": 41,
        "src": "/images/archive/best/s3.jpg",
        "zoom": "/images/archive/best/s3@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Quantitative Analysis",
        "role": "process"
      },
      {
        "n": 4,
        "page": 42,
        "src": "/images/archive/best/s4.jpg",
        "zoom": "/images/archive/best/s4@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "USER INTERVIEW SLIDES",
        "role": "process"
      },
      {
        "n": 5,
        "page": 43,
        "src": "/images/archive/best/s5.jpg",
        "zoom": "/images/archive/best/s5@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "Understanding the user",
        "role": "process"
      },
      {
        "n": 6,
        "page": 44,
        "src": "/images/archive/best/s6.jpg",
        "zoom": "/images/archive/best/s6@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "ACTIONABLE INSIGHTS",
        "role": "results"
      },
      {
        "n": 7,
        "page": 45,
        "src": "/images/archive/best/s7.jpg",
        "zoom": "/images/archive/best/s7@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "HOME PAGE",
        "role": "features"
      },
      {
        "n": 8,
        "page": 46,
        "src": "/images/archive/best/s8.jpg",
        "zoom": "/images/archive/best/s8@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "EXPLORE",
        "role": "features"
      },
      {
        "n": 9,
        "page": 47,
        "src": "/images/archive/best/s9.jpg",
        "zoom": "/images/archive/best/s9@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "TRACK",
        "role": "features"
      },
      {
        "n": 10,
        "page": 48,
        "src": "/images/archive/best/s10.jpg",
        "zoom": "/images/archive/best/s10@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "BOARD",
        "role": "features"
      },
      {
        "n": 11,
        "page": 49,
        "src": "/images/archive/best/s11.jpg",
        "zoom": "/images/archive/best/s11@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "BOARD PAGE",
        "role": "features"
      },
      {
        "n": 12,
        "page": 50,
        "src": "/images/archive/best/s12.jpg",
        "zoom": "/images/archive/best/s12@2x.jpg",
        "w": 1600,
        "h": 900,
        "label": "DETAILS PAGE",
        "role": "features"
      }
    ]
  }
];

export function getArchiveProject(slug: string): ArchiveProject | undefined {
  return ARCHIVE_PROJECTS.find((p) => p.slug === slug);
}
